name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature  # Optional: run tests also on feature branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test  # Or any test script you have

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch push

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # If you have a build step (e.g., React frontend build)

    - name: Deploy
      run: |
        echo "Add your deploy commands here"
        # For example, SSH into your server and pull the latest changes
        # or use Firebase, Heroku, Vercel CLI, etc.
